### ISSUE TITLE
Different behavior in Ed25519KeyPair's verify method in Node 10 VS 12

### ISSUE THREAD

**Issue by gjgd** [digitalbazaar/crypto-ld#44]
I created a test to reproduce the error:
https://gist.github.com/gjgd/8117bb3b2b3f1cbb79c170e5125b27bf

In Node12, both tests pass (ie the verify method returns `{ verified: true }` with a valid jws, and `{ verified: false }` with an invalid jws)

In Node10, the second test fails (ie the verify method returns `{ verified: true }` with a valid jws, and `{ verified: true }` with an invalid jws)

I tracked down the bug to this part of the crypto-ld's library:

https://github.com/digitalbazaar/crypto-ld/blob/eb00eb73687d1371fd04281ae082eb91bfa4c52d/lib/Ed25519KeyPair.js#L522-L557

In the first part of the condition (Node 12), if there is garbage at the end of the signature, the signature will be invalid
However in the second part of the condition (Node 10), if there is garbage at the end of the signature, the signature will still be valid because the end of the signature will be ignored

**Comment by aljones15** [comment]
@gjgd thanks for the bug and I was able replicate it in jest using your script. Not sure on the time frame for fixing this (I hope this is not terribly critical), but I will add your test using mocha with the PR so our CI picks it up and tests in node 10 and node 12. Thanks again.

**Comment by aljones15** [comment]
@gjgd I could be wrong here, but it looks like sodium-native might consider this a feature: https://github.com/sodium-friends/sodium-native/tree/v2.3.0

var bool = crypto_sign_verify_detached(signature, message, publicKey)

Verify a signature.

    signature should be a buffer with length crypto_sign_BYTES.
    message should be a buffer of any length.
    publicKey should be a public key.

I'm not completely sure this is a bug on our side. It might actually be with `sodium-native`

**Comment by aljones15** [comment]
@gjgd I expanded your test this morning and found the following in node10:

```js 
   const clone = json => JSON.parse(JSON.stringify(json));
    it('should not verify a signature with noise at the beginning', async () => {
      const suite = new Ed25519Signature2018();
      const noiseAtTheStart = clone(credential);
      noiseAtTheStart.proof.jws = 'somenoiseattheendofthesignature' + noiseAtTheStart.proof.jws;
      const result = await vcjs.verifyCredential({
        credential: noiseAtTheStart,
        suite,
        documentLoader,
      }); 
      expect(result.verified).toBeFalsy();
    }); 
```

so basically if the noise is at the beginning `sodium-native` fails the verification and the test passes with verified = false. This suggests that the signature is cut off when it reaches the crypto_sign_BYTES length. So it looks like this bug is either in `sodium-native` or possibly (and quite likely) in `sodium` itself as the C library probably has to construct a fixed length array of the signature's expected byte size. I'm have not done a lot of C so the last sentence might not be the most accurate technical jargon, but I think it gets the point across? 

Here is the  c binding:

https://github.com/sodium-friends/sodium-native/blob/567aad40b4ab3309cdfbf951582502a464483e19/binding.c#L357-L368

It looks like `sodium-native` might need to ensure the signature does not exceed the expected bytes I think they are just checking if it is less than the expected bytes.

So my confidence continues to grow that this is actually an error (for once) on our side =)

again THANK YOU for the awesome bug report and loved debugging this one.

**Comment by gjgd** [comment]
Thanks for looking into this so quickly! Yes I agree with you analysis

I belive the reason you are seeing the signature verification fail when you have noise at the beginning, and succeed when it's at the end is this line here:
https://github.com/digitalbazaar/crypto-ld/blob/eb00eb73687d1371fd04281ae082eb91bfa4c52d/lib/Ed25519KeyPair.js#L552 it seems the correct offset is passed so that the noise at the end which is not part of the jws is ignored.

It seems the function that calculates the correct offset is this one: https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/util.js#L182-L206

**Comment by gjgd** [comment]
To your other point: I think even if it's a bug in the sodium-native lib, there should be a check in your lib that enforces the same behavior in both node 10 and node 12

**Comment by dmitrizagidulin** [comment]
This issue no longer applies as of the `v4.0.0` version of this library:

1. Ed25519 key pair class has been extracted and moved to its own standalone repo, https://github.com/digitalbazaar/ed25519-verification-key-2018
2. The usage of `sodium-native` has been removed.

This issue can be closed.
